---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
      timezone: "Europe/Zurich"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
      timezone: "Europe/Zurich"
